---
- name: Update apt
  become: true
  apt: update_cache=yes

- name: Install System Packages
  become: true
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python-software-properties
    - openssl

- name: Install Extra 
  become: true
  apt: pkg={{ item }} state=latest
  with_items: "{{ server_packages }}"
  when: server_packages is defined

- name: Configure the timezone
  become: true
  copy: content="{{ timezone }}"
        dest="{{timezone_file}}"

# - name: More Configuration of timezone
#   file: src=/usr/share/zoneinfo/{{server.timezone}} dest=/etc/localtime state=link force=yes backup=yes

# - name: Set default system language pack
#   shell: locale-gen {{server.locale}}